# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:57:00+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Error(BaseModel):
    title: Optional[str] = Field(
        None, description='Error message', examples=['Missing API Key']
    )


class AuthFailed(BaseModel):
    errors: Optional[List[Error]] = None


class ImprovementProgramJson(BaseModel):
    image_file_b64: Optional[str] = Field(
        None,
        description='Source image file (base64-encoded string). (If this parameter is present, the other image source parameters must be empty.)',
        examples=[''],
    )
    image_filename: Optional[str] = Field(
        None,
        description='Filename of the image, if not provided it will be autodetected form the submitted data.',
        examples=['car.jpg'],
    )
    image_url: Optional[str] = Field(
        None,
        description='Source image URL. (If this parameter is present, the other image source parameters must be empty.)',
        examples=['https://www.remove.bg/example-hd.jpg'],
    )
    tag: Optional[str] = Field(
        None,
        description='Images with the same tag are grouped together.',
        examples=['batch_1_2020'],
    )


class ImprovementProgramJsonResponse(BaseModel):
    id: Optional[str] = Field(
        None,
        description='ID of the submitted image',
        examples=['fe09820b-be79-4511-8836-679583529882'],
    )


class ImprovementProgramMultipart(BaseModel):
    image_file: Optional[bytes] = Field(
        None,
        description='Source image file (binary). (If this parameter is present, the other image source parameters must be empty.)',
    )
    image_file_b64: Optional[str] = Field(
        None,
        description='Source image file (base64-encoded string). (If this parameter is present, the other image source parameters must be empty.)',
        examples=[''],
    )
    image_filename: Optional[str] = Field(
        None,
        description='Filename of the image, if not provided it will be autodetected form the submitted data.',
    )
    image_url: Optional[str] = Field(
        None,
        description='Source image URL. (If this parameter is present, the other image source parameters must be empty.)',
        examples=['https://www.remove.bg/example-hd.jpg'],
    )
    tag: Optional[str] = Field(
        None, description='Images with the same tag are grouped together.'
    )


class Error1(BaseModel):
    title: Optional[str] = Field(
        None, description='Error message', examples=['Rate limit exceeded']
    )


class RateLimit(BaseModel):
    errors: Optional[List[Error1]] = None


class Channels(Enum):
    rgba = 'rgba'
    alpha = 'alpha'


class Format(Enum):
    auto = 'auto'
    png = 'png'
    jpg = 'jpg'
    zip = 'zip'


class Size(Enum):
    preview = 'preview'
    full = 'full'
    auto = 'auto'


class Type(Enum):
    auto = 'auto'
    person = 'person'
    product = 'product'
    car = 'car'


class TypeLevel(Enum):
    none = 'none'
    field_1 = 1
    field_2 = 2
    latest = 'latest'


class RemoveBgJson(BaseModel):
    add_shadow: Optional[bool] = Field(
        'false',
        description='Whether to add an artificial shadow to the result (default: false). NOTE: Adding shadows is currently only supported for car photos. Other subjects are returned without shadow, even if set to true (this might change in the future).\n',
    )
    bg_color: Optional[str] = Field(
        None,
        description='Adds a solid color background. Can be a hex color code (e.g. 81d4fa, fff) or a color name (e.g. green). For semi-transparency, 4-/8-digit hex codes are also supported (e.g. 81d4fa77). (If this parameter is present, the other bg_ parameters must be empty.)\n',
        examples=[''],
    )
    bg_image_url: Optional[str] = Field(
        None,
        description='Adds a background image from a URL. The image is centered and resized to fill the canvas while preserving the aspect ratio, unless it already has the exact same dimensions as the foreground image. (If this parameter is present, the other bg_ parameters must be empty.)',
        examples=[''],
    )
    channels: Optional[Channels] = Field(
        'rgba',
        description='Request either the finalized image ("rgba", default) or an alpha mask ("alpha"). Note: Since remove.bg also applies RGB color corrections on edges, using only the alpha mask often leads to a lower final image quality. Therefore "rgba" is recommended.\n',
    )
    crop: Optional[bool] = Field(
        'false',
        description='Whether to crop off all empty regions (default: false). Note that cropping has no effect on the amount of charged credits.\n',
    )
    crop_margin: Optional[str] = Field(
        '0',
        description='Adds a margin around the cropped subject (default: 0). Can be an absolute value (e.g. "30px") or relative to the subject size (e.g. "10%"). Can be a single value (all sides), two values (top/bottom and left/right) or four values (top, right, bottom, left). This parameter only has an effect when "crop=true". The maximum margin that can be added on each side is 50% of the subject dimensions or 500 pixels.\n',
    )
    format: Optional[Format] = Field(
        'auto',
        description='Result image format:\n"auto" = Use PNG format if transparent regions exist, otherwise use JPG format (default),\n"png" = PNG format with alpha transparency,\n"jpg" = JPG format, no transparency,\n"zip" = ZIP format, contains color image and alpha matte image, supports transparency (recommended).\n',
    )
    image_file_b64: Optional[str] = Field(
        None,
        description='Source image file (base64-encoded string). (If this parameter is present, the other image source parameters must be empty.)',
        examples=[''],
    )
    image_url: Optional[str] = Field(
        None,
        description='Source image URL. (If this parameter is present, the other image source parameters must be empty.)',
        examples=['https://www.remove.bg/example-hd.jpg'],
    )
    position: Optional[str] = Field(
        'original',
        description='Positions the subject within the image canvas. Can be "original" (default unless "scale" is given), "center" (default when "scale" is given) or a value from "0%" to "100%" (both horizontal and vertical) or two values (horizontal, vertical).\n',
    )
    roi: Optional[str] = Field(
        '0% 0% 100% 100%',
        description='Region of interest: Only contents of this rectangular region can be detected as foreground. Everything outside is considered background and will be removed. The rectangle is defined as two x/y coordinates in the format "x1 y1 x2 y2". The coordinates can be in absolute pixels (suffix \'px\') or relative to the width/height of the image (suffix \'%\'). By default, the whole image is the region of interest ("0% 0% 100% 100%").\n',
    )
    scale: Optional[str] = Field(
        'original',
        description='Scales the subject relative to the total image size. Can be any value from "10%" to "100%", or "original" (default). Scaling the subject implies "position=center" (unless specified otherwise).\n',
    )
    semitransparency: Optional[bool] = Field(
        'true',
        description='Whether to have semi-transparent regions in the result (default: true). NOTE: Semitransparency is currently only supported for car windows (this might change in the future). Other objects are returned without semitransparency, even if set to true.\n',
    )
    size: Optional[Size] = Field(
        'preview',
        description='Maximum output image resolution:\n"preview" (default) = Resize image to 0.25 megapixels (e.g. 625×400 pixels) – 0.25 credits per image,\n"full" = Use original image resolution, up to 25 megapixels (e.g. 6250x4000) with formats ZIP or JPG, or up to 10 megapixels (e.g. 4000x2500) with PNG – 1 credit per image),\n"auto" = Use highest available resolution (based on image size and available credits).\n\nFor backwards-compatibility this parameter also accepts the values "medium" (up to 1.5 megapixels) and "hd" (up to 4 megapixels) for 1 credit per image. The value "full" is also available under the name "4k" and the value "preview" is aliased as "small" and "regular".\n',
    )
    type: Optional[Type] = Field(
        'auto',
        description='Foreground type:\n"auto" = Automatically detect kind of foreground,\n"person" = Use person(s) as foreground,\n"product" = Use product(s) as foreground.\n"car" = Use car as foreground,\n',
    )
    type_level: Optional[TypeLevel] = Field(
        1,
        description='Classification level of the detected foreground type:\n"none" = No classification (X-Type Header won\'t bet set on the response)\n"1" = Use coarse classification classes: [person, product, animal, car, other]\n"2" = Use more specific classification classes: [person, product, animal, car, car_interior, car_part, transportation, graphics, other]\n"latest" = Always use the latest classification classes available\n',
    )


class Data(BaseModel):
    foreground_height: Optional[int] = Field(
        None,
        description='Height of the foreground image. In case the input image resolution is higher than the limit (> 25 megapixels) this value is expressed with respect to the input image resolution.',
        examples=[100],
    )
    foreground_left: Optional[int] = Field(
        None,
        description='Left position of the foreground image along the horizontal axis. In case the input image resolution is higher than the limit (> 25 megapixels) this value is expressed with respect to the input image resolution.',
        examples=[0],
    )
    foreground_top: Optional[int] = Field(
        None,
        description='Top position of the foreground image along the vertical axis. In case the input image resolution is higher than the limit (> 25 megapixels) this value is expressed with respect to the input image resolution.',
        examples=[0],
    )
    foreground_width: Optional[int] = Field(
        None,
        description='Width of the foreground image. In case the input image resolution is higher than the limit (> 25 megapixels) this value is expressed with respect to the input image resolution.',
        examples=[100],
    )
    result_b64: Optional[str] = Field(
        None,
        description='Base64 encoded string of result image',
        examples=['iVBORw0KGgoAAAANSUhEUgAAAIsAAACFC...'],
    )


class RemoveBgJsonResponse(BaseModel):
    data: Optional[Data] = None


class RemoveBgMultipart(BaseModel):
    add_shadow: Optional[bool] = Field(
        'false',
        description='Whether to add an artificial shadow to the result (default: false). NOTE: Adding shadows is currently only supported for car photos. Other subjects are returned without shadow, even if set to true (this might change in the future).\n',
    )
    bg_color: Optional[str] = Field(
        None,
        description='Adds a solid color background. Can be a hex color code (e.g. 81d4fa, fff) or a color name (e.g. green). For semi-transparency, 4-/8-digit hex codes are also supported (e.g. 81d4fa77). (If this parameter is present, the other bg_ parameters must be empty.)\n',
        examples=[''],
    )
    bg_image_file: Optional[bytes] = Field(
        None,
        description='Adds a background image from a file (binary). The image is centered and resized to fill the canvas while preserving the aspect ratio, unless it already has the exact same dimensions as the foreground image. (If this parameter is present, the other bg_ parameters must be empty.)',
    )
    bg_image_url: Optional[str] = Field(
        None,
        description='Adds a background image from a URL. The image is centered and resized to fill the canvas while preserving the aspect ratio, unless it already has the exact same dimensions as the foreground image. (If this parameter is present, the other bg_ parameters must be empty.)',
        examples=[''],
    )
    channels: Optional[Channels] = Field(
        'rgba',
        description='Request either the finalized image ("rgba", default) or an alpha mask ("alpha"). Note: Since remove.bg also applies RGB color corrections on edges, using only the alpha mask often leads to a lower final image quality. Therefore "rgba" is recommended.\n',
    )
    crop: Optional[bool] = Field(
        'false',
        description='Whether to crop off all empty regions (default: false). Note that cropping has no effect on the amount of charged credits.\n',
    )
    crop_margin: Optional[str] = Field(
        '0',
        description='Adds a margin around the cropped subject (default: 0). Can be an absolute value (e.g. "30px") or relative to the subject size (e.g. "10%"). Can be a single value (all sides), two values (top/bottom and left/right) or four values (top, right, bottom, left). This parameter only has an effect when "crop=true". The maximum margin that can be added on each side is 50% of the subject dimensions or 500 pixels.\n',
    )
    format: Optional[Format] = Field(
        'auto',
        description='Result image format:\n"auto" = Use PNG format if transparent regions exist, otherwise use JPG format (default),\n"png" = PNG format with alpha transparency,\n"jpg" = JPG format, no transparency,\n"zip" = ZIP format, contains color image and alpha matte image, supports transparency (recommended).\n',
    )
    image_file: Optional[bytes] = Field(
        None,
        description='Source image file (binary). (If this parameter is present, the other image source parameters must be empty.)',
    )
    image_file_b64: Optional[str] = Field(
        None,
        description='Source image file (base64-encoded string). (If this parameter is present, the other image source parameters must be empty.)',
        examples=[''],
    )
    image_url: Optional[str] = Field(
        None,
        description='Source image URL. (If this parameter is present, the other image source parameters must be empty.)',
        examples=['https://www.remove.bg/example-hd.jpg'],
    )
    position: Optional[str] = Field(
        'original',
        description='Positions the subject within the image canvas. Can be "original" (default unless "scale" is given), "center" (default when "scale" is given) or a value from "0%" to "100%" (both horizontal and vertical) or two values (horizontal, vertical).\n',
    )
    roi: Optional[str] = Field(
        '0% 0% 100% 100%',
        description='Region of interest: Only contents of this rectangular region can be detected as foreground. Everything outside is considered background and will be removed. The rectangle is defined as two x/y coordinates in the format "x1 y1 x2 y2". The coordinates can be in absolute pixels (suffix \'px\') or relative to the width/height of the image (suffix \'%\'). By default, the whole image is the region of interest ("0% 0% 100% 100%").\n',
    )
    scale: Optional[str] = Field(
        'original',
        description='Scales the subject relative to the total image size. Can be any value from "10%" to "100%", or "original" (default). Scaling the subject implies "position=center" (unless specified otherwise).\n',
    )
    semitransparency: Optional[bool] = Field(
        'true',
        description='Whether to have semi-transparent regions in the result (default: true). NOTE: Semitransparency is currently only supported for car windows (this might change in the future). Other objects are returned without semitransparency, even if set to true.\n',
    )
    size: Optional[Size] = Field(
        'preview',
        description='Maximum output image resolution:\n"preview" (default) = Resize image to 0.25 megapixels (e.g. 625×400 pixels) – 0.25 credits per image,\n"full" = Use original image resolution, up to 25 megapixels (e.g. 6250x4000) with formats ZIP or JPG, or up to 10 megapixels (e.g. 4000x2500) with PNG – 1 credit per image),\n"auto" = Use highest available resolution (based on image size and available credits).\n\nFor backwards-compatibility this parameter also accepts the values "medium" (up to 1.5 megapixels) and "hd" (up to 4 megapixels) for 1 credit per image. The value "full" is also available under the name "4k" and the value "preview" is aliased as "small" and "regular".\n',
    )
    type: Optional[Type] = Field(
        'auto',
        description='Foreground type:\n"auto" = Automatically detect kind of foreground,\n"person" = Use person(s) as foreground,\n"product" = Use product(s) as foreground.\n"car" = Use car as foreground,\n',
    )
    type_level: Optional[TypeLevel] = Field(
        1,
        description='Classification level of the detected foreground type:\n"none" = No classification (X-Type Header won\'t bet set on the response)\n"1" = Use coarse classification classes: [person, product, animal, car, other]\n"2" = Use more specific classification classes: [person, product, animal, car, car_interior, car_part, transportation, graphics, other]\n"latest" = Always use the latest classification classes available\n',
    )


class Api(BaseModel):
    free_calls: Optional[int] = Field(None, examples=[50])
    sizes: Optional[str] = Field(None, examples=['all'])


class Credits(BaseModel):
    enterprise: Optional[float] = Field(None, examples=[0])
    payg: Optional[float] = Field(None, examples=[50])
    subscription: Optional[float] = Field(None, examples=[150])
    total: Optional[float] = Field(None, examples=[200])


class Attributes(BaseModel):
    api: Optional[Api] = None
    credits: Optional[Credits] = None


class Data1(BaseModel):
    attributes: Optional[Attributes] = None


class AccountGetResponse(BaseModel):
    data: Optional[Data1] = None


class Error2(BaseModel):
    title: Optional[str] = Field(
        None, description='Error message', examples=['File too large']
    )


class ImprovePostResponse(BaseModel):
    errors: Optional[List[Error2]] = None


class Error3(BaseModel):
    code: Optional[str] = Field(
        None, description='Error code', examples=['file_too_large']
    )
    detail: Optional[str] = Field(
        None,
        description='Detailed description of the error',
        examples=['File exceeds limit of 12MB'],
    )
    title: Optional[str] = Field(
        None, description='Error message', examples=['File too large']
    )


class RemovebgPostResponse(BaseModel):
    errors: Optional[List[Error3]] = None


class Error4(BaseModel):
    title: Optional[str] = Field(
        None, description='Error message', examples=['Insufficient credits']
    )


class RemovebgPostResponse1(BaseModel):
    errors: Optional[List[Error4]] = None
